/**
 * Property-Based Tests for SSE Event Formatter
 *
 * **Property 1: SSE Event Format Round-Trip**
 * **Validates: Requirements 3.1, 3.2, 4.2**
 *
 * For any SSE event generated by the Streaming Lambda, parsing the event string
 * should correctly extract the event type and data fields, and re-serializing
 * should produce an equivalent event string.
 */

import * as fc from 'fast-check';
import { formatSSEEvent, parseSSEEvent } from '../sseFormatter';

describe('SSE Event Format Round-Trip Property Tests', () => {
  /**
   * Property 1: SSE Event Format Round-Trip
   *
   * For any valid event type and JSON-serializable data payload:
   * 1. formatSSEEvent produces a valid SSE string
   * 2. parseSSEEvent can parse it back
   * 3. The parsed result equals the original input
   * 4. Re-serializing produces an equivalent string
   */
  it('should round-trip any valid event type and data payload', () => {
    // Generator for valid SSE event types (alphanumeric with underscores, no newlines)
    const eventTypeArb = fc.stringOf(
      fc.constantFrom(...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_'),
      { minLength: 1, maxLength: 50 }
    );

    // Generator for JSON-serializable data objects
    // Avoiding special characters that could break JSON or SSE parsing
    const jsonValueArb: fc.Arbitrary<unknown> = fc.letrec((tie) => ({
      value: fc.oneof(
        { maxDepth: 2 },
        fc.string({ maxLength: 100 }).filter((s) => !s.includes('\n')),
        fc.integer(),
        fc.double({ noNaN: true, noDefaultInfinity: true }),
        fc.boolean(),
        fc.constant(null),
        fc.array(tie('value'), { maxLength: 5 }),
        fc.dictionary(
          fc.string({ minLength: 1, maxLength: 20 }).filter((s) => /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(s)),
          tie('value'),
          { maxKeys: 5 }
        )
      ),
    })).value;

    const dataObjectArb = fc.dictionary(
      fc.string({ minLength: 1, maxLength: 20 }).filter((s) => /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(s)),
      jsonValueArb,
      { minKeys: 1, maxKeys: 10 }
    );

    fc.assert(
      fc.property(eventTypeArb, dataObjectArb, (eventType, data) => {
        // Step 1: Serialize to SSE format
        const sseString = formatSSEEvent(eventType, data);

        // Step 2: Verify SSE format structure
        expect(sseString).toMatch(/^event: .+\ndata: .+\n\n$/);

        // Step 3: Parse back
        const parsed = parseSSEEvent(sseString);

        // Step 4: Verify parsing succeeded
        expect(parsed).not.toBeNull();

        // Step 5: Verify equality of event type
        expect(parsed!.eventType).toBe(eventType);

        // Step 6: Verify equality of data (deep comparison)
        expect(parsed!.data).toEqual(data);

        // Step 7: Re-serialize and verify equivalence
        const reserialized = formatSSEEvent(parsed!.eventType, parsed!.data);
        expect(reserialized).toBe(sseString);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Additional property: Known event types should round-trip correctly
   *
   * Tests with the actual SSE event types defined in the spec
   */
  it('should round-trip all known SSE event types from the spec', () => {
    const knownEventTypes = [
      'thinking_stream',
      'analysis_stream',
      'cdk_modules_stream',
      'optimization_stream',
      'analysis_complete',
      'cdk_modules_complete',
      'optimization_complete',
      'error',
      '[DONE]',
    ];

    const contentArb = fc.record({
      content: fc.string({ maxLength: 500 }).filter((s) => !s.includes('\n')),
    });

    fc.assert(
      fc.property(
        fc.constantFrom(...knownEventTypes),
        contentArb,
        (eventType, data) => {
          const sseString = formatSSEEvent(eventType, data);
          const parsed = parseSSEEvent(sseString);

          expect(parsed).not.toBeNull();
          expect(parsed!.eventType).toBe(eventType);
          expect(parsed!.data).toEqual(data);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property: Empty object data should round-trip correctly
   *
   * Completion events often have empty data payloads
   */
  it('should round-trip events with empty object data', () => {
    const eventTypeArb = fc.stringOf(
      fc.constantFrom(...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_'),
      { minLength: 1, maxLength: 50 }
    );

    fc.assert(
      fc.property(eventTypeArb, (eventType) => {
        const emptyData = {};
        const sseString = formatSSEEvent(eventType, emptyData);
        const parsed = parseSSEEvent(sseString);

        expect(parsed).not.toBeNull();
        expect(parsed!.eventType).toBe(eventType);
        expect(parsed!.data).toEqual(emptyData);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Property: Nested objects should round-trip correctly
   *
   * Tests complex nested data structures
   */
  it('should round-trip events with nested object data', () => {
    const nestedObjectArb = fc.record({
      level1: fc.record({
        level2: fc.record({
          value: fc.string({ maxLength: 50 }).filter((s) => !s.includes('\n')),
          count: fc.integer({ min: 0, max: 1000 }),
        }),
        items: fc.array(fc.integer(), { maxLength: 5 }),
      }),
      metadata: fc.record({
        timestamp: fc.integer({ min: 0 }),
        success: fc.boolean(),
      }),
    });

    fc.assert(
      fc.property(nestedObjectArb, (data) => {
        const eventType = 'analysis_stream';
        const sseString = formatSSEEvent(eventType, data);
        const parsed = parseSSEEvent(sseString);

        expect(parsed).not.toBeNull();
        expect(parsed!.eventType).toBe(eventType);
        expect(parsed!.data).toEqual(data);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Property: Arrays in data should round-trip correctly
   */
  it('should round-trip events with array data', () => {
    const arrayDataArb = fc.record({
      items: fc.array(
        fc.oneof(
          fc.string({ maxLength: 30 }).filter((s) => !s.includes('\n')),
          fc.integer(),
          fc.boolean()
        ),
        { maxLength: 10 }
      ),
    });

    fc.assert(
      fc.property(arrayDataArb, (data) => {
        const eventType = 'cdk_modules_stream';
        const sseString = formatSSEEvent(eventType, data);
        const parsed = parseSSEEvent(sseString);

        expect(parsed).not.toBeNull();
        expect(parsed!.eventType).toBe(eventType);
        expect(parsed!.data).toEqual(data);
      }),
      { numRuns: 100 }
    );
  });
});
